//! Google Indexing API submission, against a local mock server.
//!
//! Assertions here are signed with a real RSA key, generated by `common`, so
//! signing is genuinely exercised. Each service account's `token_uri` points at
//! the mock server.

mod common;

use std::sync::{Arc, Mutex};
use std::time::Duration;

use base64::Engine as _;
use common::service_account;
use httpmock::MockServer;
use indeks::credentials::Credential;
use indeks::engine::google::{Backoff, Google, SCOPE};
use indeks::engine::{Kind, Submitter};
use url::Url;

const ACCESS_TOKEN: &str = "ya29.test-access-token";

fn urls(values: &[&str]) -> Vec<Url> {
    values.iter().map(|v| Url::parse(v).unwrap()).collect()
}

/// A mock token endpoint that hands out [`ACCESS_TOKEN`].
fn mock_token_endpoint(server: &MockServer) -> httpmock::Mock<'_> {
    server.mock(|when, then| {
        when.method("POST").path("/token");
        then.status(200).json_body(serde_json::json!({
            "access_token": ACCESS_TOKEN,
            "expires_in": 3599,
            "token_type": "Bearer",
        }));
    })
}

fn engine(server: &MockServer, credential: Credential) -> Google {
    Google {
        credential,
        client: reqwest::blocking::Client::new(),
        endpoint: server.url("/publish"),
        // Retry immediately: these tests are about how many attempts happen,
        // not how long they wait.
        backoff: Backoff {
            attempts: 2,
            first_wait: Duration::ZERO,
        },
    }
}

/// A 429 body naming the quota the way Google does.
fn quota_body(metric: &str) -> serde_json::Value {
    serde_json::json!({
        "error": {
            "code": 429,
            "message": format!(
                "Quota exceeded for quota metric 'Publish requests' and limit '{metric}' \
                 of service 'indexing.googleapis.com' for consumer 'project_number:1'."
            ),
            "status": "RESOURCE_EXHAUSTED",
        }
    })
}

#[test]
fn exchanges_an_assertion_then_publishes_each_url() {
    let server = MockServer::start();
    let token = mock_token_endpoint(&server);
    let publish = server.mock(|when, then| {
        when.method("POST")
            .path("/publish")
            .header("authorization", format!("Bearer {ACCESS_TOKEN}"));
        then.status(200).json_body(serde_json::json!({
            "urlNotificationMetadata": { "url": "https://example.com/a" }
        }));
    });

    let credential = Credential::File(service_account(&server.url("/token")));
    let outcomes = engine(&server, credential)
        .submit(&urls(&["https://example.com/a", "https://example.com/b"]))
        .unwrap();

    // One token exchange for the run, one publish per URL.
    assert_eq!(token.calls(), 1);
    assert_eq!(publish.calls(), 2);
    assert_eq!(outcomes.len(), 2);
    assert!(outcomes.iter().all(|o| o.succeeded()));
}

#[test]
fn sends_the_notification_google_expects() {
    let server = MockServer::start();
    mock_token_endpoint(&server);
    let publish = server.mock(|when, then| {
        when.method("POST")
            .path("/publish")
            .json_body(serde_json::json!({
                "url": "https://example.com/a",
                "type": "URL_UPDATED",
            }));
        then.status(200);
    });

    let credential = Credential::File(service_account(&server.url("/token")));
    engine(&server, credential)
        .submit(&urls(&["https://example.com/a"]))
        .unwrap();

    publish.assert();
}

/// Decode one segment of a JWT, without verifying it.
fn segment(token: &str, index: usize) -> serde_json::Value {
    let part = token.split('.').nth(index).expect("missing JWT segment");
    let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(part)
        .expect("segment is not base64url");
    serde_json::from_slice(&bytes).expect("segment is not JSON")
}

/// Every claim Google checks on an assertion.
///
/// Wrong values here are rejected by the real token endpoint — an `iat` that is
/// not wall-clock draws "Invalid JWT: Token must be a short-lived token" — so
/// each is worth pinning. The assertion is captured rather than matched on, so a
/// failure names the claim that was wrong instead of just missing the mock.
#[test]
fn signs_an_assertion_google_would_accept() {
    let server = MockServer::start();
    let token_uri = server.url("/token");

    let captured: Arc<Mutex<Option<String>>> = Arc::new(Mutex::new(None));
    let sink = Arc::clone(&captured);

    server.mock(move |when, then| {
        when.method("POST").path("/token").is_true(move |request| {
            *sink.lock().unwrap() = Some(String::from_utf8_lossy(request.body_ref()).into_owned());
            true
        });
        then.status(200).json_body(serde_json::json!({
            "access_token": ACCESS_TOKEN,
            "expires_in": 3599,
            "token_type": "Bearer",
        }));
    });
    server.mock(|when, then| {
        when.method("POST").path("/publish");
        then.status(200);
    });

    let credential = Credential::File(service_account(&token_uri));
    engine(&server, credential)
        .submit(&urls(&["https://example.com/a"]))
        .unwrap();

    let body = captured
        .lock()
        .unwrap()
        .clone()
        .expect("token never called");
    let (grant, assertion) = (
        body.split('&')
            .find_map(|pair| pair.strip_prefix("grant_type="))
            .expect("no grant_type"),
        body.split('&')
            .find_map(|pair| pair.strip_prefix("assertion="))
            .expect("no assertion"),
    );

    assert_eq!(
        grant,
        "urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer"
    );
    assert_eq!(assertion.split('.').count(), 3, "{assertion}");
    assert_eq!(segment(assertion, 0)["alg"], "RS256");

    let claims = segment(assertion, 1);
    assert_eq!(claims["iss"], common::CLIENT_EMAIL);
    assert_eq!(claims["scope"], SCOPE);
    assert_eq!(claims["aud"], token_uri);

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();
    let issued_at = claims["iat"].as_u64().expect("iat is not a number");
    let expires = claims["exp"].as_u64().expect("exp is not a number");

    assert!(issued_at.abs_diff(now) < 60, "iat {issued_at} vs now {now}");
    assert!(expires > now, "exp {expires} is not ahead of {now}");
    assert_eq!(expires - issued_at, 3600, "assertion should last an hour");
}

/// Moved here from a unit test: `ServiceAccount::load` needs a real key to parse,
/// and the key now comes from a dev-dependency rather than a build script.
#[test]
fn accepts_a_generated_service_account() {
    let path = service_account(common::GOOGLE_TOKEN_URI);
    let credential = Credential::File(path);

    assert!(indeks::engine::google::check_credential(&credential).is_ok());
    assert!(Kind::Google.check_credential(&credential).is_ok());
}

#[test]
fn a_bare_token_skips_the_token_endpoint() {
    let server = MockServer::start();
    let token = mock_token_endpoint(&server);
    let publish = server.mock(|when, then| {
        when.method("POST")
            .path("/publish")
            .header("authorization", "Bearer ya29.given-directly");
        then.status(200);
    });

    let credential = Credential::Token("ya29.given-directly".to_string());
    let outcomes = engine(&server, credential)
        .submit(&urls(&["https://example.com/a"]))
        .unwrap();

    assert_eq!(token.calls(), 0, "no assertion should have been exchanged");
    assert_eq!(publish.calls(), 1);
    assert!(outcomes[0].succeeded());
}

#[test]
fn reports_a_permission_failure_with_googles_own_message() {
    let server = MockServer::start();
    mock_token_endpoint(&server);
    server.mock(|when, then| {
        when.method("POST").path("/publish");
        then.status(403).json_body(serde_json::json!({
            "error": {
                "code": 403,
                "message": "Permission denied. Failed to verify the URL ownership.",
                "status": "PERMISSION_DENIED",
            }
        }));
    });

    let credential = Credential::File(service_account(&server.url("/token")));
    let outcomes = engine(&server, credential)
        .submit(&urls(&["https://example.com/a"]))
        .unwrap();

    let error = outcomes[0].error.as_ref().unwrap();
    assert_eq!(outcomes[0].status, 403);
    assert!(
        error.contains("Failed to verify the URL ownership"),
        "{error}"
    );
    assert!(
        error.contains("owner of the property in Search Console"),
        "{error}"
    );
}

#[test]
fn retries_a_per_minute_limit_and_carries_on() {
    let server = MockServer::start();
    mock_token_endpoint(&server);

    // Rate limited once, then fine.
    let limited = server.mock(|when, then| {
        when.method("POST").path("/publish").body_includes("/a");
        then.status(429)
            .json_body(quota_body("Requests per minute"));
    });
    let ok = server.mock(|when, then| {
        when.method("POST").path("/publish").body_includes("/b");
        then.status(200);
    });

    let credential = Credential::File(service_account(&server.url("/token")));
    let outcomes = engine(&server, credential)
        .submit(&urls(&["https://example.com/a", "https://example.com/b"]))
        .unwrap();

    // Three attempts at /a: the first plus two retries, all refused.
    assert_eq!(limited.calls(), 3);
    // A per-minute limit that never clears still stops the run, so /b is not
    // attempted — but the message says retrying was tried.
    assert_eq!(ok.calls(), 0);
    assert!(
        outcomes[1]
            .error
            .as_ref()
            .unwrap()
            .contains("still rate limited after retrying"),
        "{:?}",
        outcomes[1]
    );
}

#[test]
fn a_per_minute_limit_that_clears_lets_the_run_finish() {
    let server = MockServer::start();
    mock_token_endpoint(&server);

    let mut sequence = server.mock(|when, then| {
        when.method("POST").path("/publish");
        then.status(429)
            .json_body(quota_body("Requests per minute"));
    });
    let credential = Credential::File(service_account(&server.url("/token")));
    let google = engine(&server, credential);

    // First attempt is refused; by the retry the limit has cleared.
    sequence.delete();
    let publish = server.mock(|when, then| {
        when.method("POST").path("/publish");
        then.status(200);
    });

    let outcomes = google.submit(&urls(&["https://example.com/a"])).unwrap();

    assert_eq!(publish.calls(), 1);
    assert!(outcomes[0].succeeded(), "{:?}", outcomes[0]);
}

#[test]
fn does_not_retry_the_daily_quota() {
    let server = MockServer::start();
    mock_token_endpoint(&server);
    let publish = server.mock(|when, then| {
        when.method("POST").path("/publish");
        then.status(429)
            .json_body(quota_body("Publish requests per day"));
    });

    let credential = Credential::File(service_account(&server.url("/token")));
    let outcomes = engine(&server, credential)
        .submit(&urls(&["https://example.com/a", "https://example.com/b"]))
        .unwrap();

    // Waiting cannot help before midnight Pacific, so exactly one attempt.
    assert_eq!(publish.calls(), 1);
    assert!(
        outcomes[0]
            .error
            .as_ref()
            .unwrap()
            .contains("resets at midnight Pacific")
    );
    assert!(
        outcomes[1]
            .error
            .as_ref()
            .unwrap()
            .contains("the daily publish quota is spent")
    );
}

#[test]
fn honours_retry_after_when_the_server_sends_one() {
    let server = MockServer::start();
    mock_token_endpoint(&server);
    let publish = server.mock(|when, then| {
        when.method("POST").path("/publish");
        then.status(429)
            .header("retry-after", "0")
            .json_body(quota_body("Requests per minute"));
    });

    let credential = Credential::File(service_account(&server.url("/token")));
    engine(&server, credential)
        .submit(&urls(&["https://example.com/a"]))
        .unwrap();

    assert_eq!(publish.calls(), 3);
}

#[test]
fn stops_submitting_once_rate_limited() {
    let server = MockServer::start();
    mock_token_endpoint(&server);
    let publish = server.mock(|when, then| {
        when.method("POST").path("/publish");
        then.status(429)
            .json_body(quota_body("Publish requests per day"));
    });

    let credential = Credential::File(service_account(&server.url("/token")));
    let outcomes = engine(&server, credential)
        .submit(&urls(&[
            "https://example.com/a",
            "https://example.com/b",
            "https://example.com/c",
        ]))
        .unwrap();

    // Every URL is still accounted for, but only the first was actually sent.
    assert_eq!(publish.calls(), 1);
    assert_eq!(outcomes.len(), 3);
    assert!(
        outcomes[0]
            .error
            .as_ref()
            .unwrap()
            .contains("the daily publish quota is spent")
    );
    assert!(
        outcomes[1]
            .error
            .as_ref()
            .unwrap()
            .starts_with("not attempted")
    );
    assert!(
        outcomes[2]
            .error
            .as_ref()
            .unwrap()
            .starts_with("not attempted")
    );
}

#[test]
fn a_refused_assertion_fails_the_run() {
    let server = MockServer::start();
    server.mock(|when, then| {
        when.method("POST").path("/token");
        then.status(400).json_body(serde_json::json!({
            "error": "invalid_grant",
            "error_description": "Invalid JWT Signature.",
        }));
    });
    let publish = server.mock(|when, then| {
        when.method("POST").path("/publish");
        then.status(200);
    });

    let credential = Credential::File(service_account(&server.url("/token")));
    let error = engine(&server, credential)
        .submit(&urls(&["https://example.com/a"]))
        .unwrap_err();

    assert_eq!(publish.calls(), 0, "nothing should have been published");
    assert!(
        error.to_string().contains("the token endpoint at"),
        "{error}"
    );
}

#[test]
fn a_token_endpoint_that_answers_nonsense_fails_the_run() {
    let server = MockServer::start();
    server.mock(|when, then| {
        when.method("POST").path("/token");
        then.status(200).body("not json");
    });

    let credential = Credential::File(service_account(&server.url("/token")));
    let error = engine(&server, credential)
        .submit(&urls(&["https://example.com/a"]))
        .unwrap_err();

    assert!(
        error.to_string().contains("did not return an access token"),
        "{error}"
    );
}
